### ISSUE TITLE
Error on creating the output

### ISSUE THREAD

**Issue by Amro-Hassan** [cole-brokamp/DeGAUSS#18] opened 2019-09-10 20:52 UTC
Loading required package: methods
Warning message:
In scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  :
  EOF within quoted string
Error in `[.data.frame`(addresses, , address.col.name) :
  undefined columns selected
Calls: unique -> [ -> [.data.frame
Execution halted

**Comment by cole-brokamp** [comment] 2019-09-10 21:17
Hi, can you please report the code along with an input CSV file (even if one of the examples) so that I can recreate the problem in order to help troubleshoot your issue?

**Comment by Amro-Hassan** [comment] 2019-09-11 15:37
Hi Cole,
Thanks for getting back to me, 

1) I went to the Specific Folder in CMD
By using CD C:\Users\Admin\Desktop\CDM v5.0\New folder
2) since I'm using windows I replaced "$PWD" with "%cd%"
docker run --rm=TRUE -v "%cd%":/tmp degauss/geocoder GeoCodesSample.csv address

sample data attached, data is de-identified so I don't expect it to return actual results.

[GeoCodesSample.zip](https://github.com/cole-brokamp/DeGAUSS/files/3601572/GeoCodesSample.zip)

**Comment by cole-brokamp** [comment] 2019-09-11 17:02
Thanks, looks like you are running everything correctly except that you should be using `Address` instead of `address` in your call.  The tool is looking for the column called `address`, but can't find it -- we could probably make a more friendly error message for this case.  Closing for now as I tried to reproduce locally and correcting the call fixed the problem.  Please reopen if you have any other questions.

**Closed as completed by cole-brokamp** 2019-09-11 17:02 UTC
